### ISSUE TITLE
Overwritable output

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/histoprint#19]
I would love to use `print_hist` as a sort of physics aware tqdm. Is there a way to overwrite the last output histogram easily? If not this would be a super useful feature :)

**Comment by ast0815** [comment]
Histoprint has no concept of persistent objects or "things that will be drawn later" like Matplotlib has. It is much more primitive than that. You give it one or more histograms, it prints those, it is done. So there is no way to edit a printed histogram after its creation.

There is nothing stopping you from repeatedly drawing the updated histogram(s) though. If you want some sort of updating "dashboard" in the console, you could use `click.clear()` https://click.palletsprojects.com/en/7.x/api/?highlight=clear#click.clear to clear the screen before printing an updated version. This probably won't work with Jupyter Lab or similar though.

Also, what's a "tqdm"?

**Comment by eduardo-rodrigues** [comment]
For info, @ast0815 - tqdm is a powerful and popular package for progress bars, see https://tqdm.github.io/.

**Comment by ast0815** [comment]
Ah, I might have misunderstood the question? If the aim is to actually re-draw on the same position on screen (rather than updating a drawing object in memory), that might be a bit difficult. I imagine re-drawing multiple lines is a bit harder than just "printing backspaces" to redraw in the current one, though it would be a neat feature indeed.

As a stop-gap solution, one could definitely use `click.clear` (https://click.palletsprojects.com/en/7.x/api/?highlight=clear#click.clear) to just clear the whole terminal screen before each loop iteration of drawing the histogram.

**Comment by andrzejnovak** [comment]
Just for reference, I got a prototype working with `rich` but couldn't solve the annoying flickr.
![](https://i.imgur.com/KRneQOY.gif)

**Comment by ast0815** [comment]
That's pretty cool!

Maybe the flicker can be solved by limiting the update frequency? Simplest case would be to only actually clear and draw every N updates. Though maybe you already tried that. 😄

**Comment by ast0815** [comment]
Looking into `rich` a bit, it might be a good idea to make `HistFormatter` a printable object by giving it a `__rich__` method. Combined with giving it a way to update the data it will print, this might make it quite powerful.
